### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by solevis** [PSS-Tools-Development/pssapi.py#1]
https://docs.pytest.org/

**Comment by Zukunftsmusik** [comment]
There's a testing library that records, stores and replays http requests: https://vcrpy.readthedocs.io/en/latest/
Not sure, yet, if it works with async requests (aiohttp) as well.

Also unit tests for services and entities should be auto-generated.

**Comment by Zukunftsmusik** [comment]
I was playing around with v0.2.0 and found out that we can't rely on Savy using the same case for strings denoting a StrEnum. E.g. the enum `LanguageKey` has values in lower case, but the endpoint `AllianceService.list_alliances_with_ranking` returns a language code in all uppercase.

Before we proceed, we should probably write tests for each endpoint.

**Comment by Zukunftsmusik** [comment]
Create client and use it for multiple endpoint tests: https://stackoverflow.com/questions/37251892/pytest-create-an-object-shared-by-multiple-tests
