### ISSUE TITLE
Implement caching for entities with versions

### ISSUE THREAD

**Issue by Zukunftsmusik** [PSS-Tools-Development/pssapi.py#4]
Any endpoint that returns entities and a data version should be cached. The client would check the LatestSettings endpoint to get the current data versions, check if it matches the one in the cache and either update the cache (if there's no match) or not. For those endpoints, data will always be returned from the cache.

Also there should be an option when creating a client to disable the cache.

**Comment by solevis** [comment]
Not tested, but https://pypi.org/project/cachetools/ seems a pretty nice module to handle this issue (just need to extend the Cache class and use data version to determine expiration).

**Comment by Zukunftsmusik** [comment]
Interesting. Will have a look.

**Comment by Zukunftsmusik** [comment]
There's a testing library that records, stores and replays http requests: https://vcrpy.readthedocs.io/en/latest/
Not sure, yet, if it works with async requests (aiohttp) as well.

Also unit tests for services and entities should be auto-generated.

**Comment by Zukunftsmusik** [comment]
Implemented caching by version number in the code generation. Initial tests were successful.
