### ISSUE TITLE
Can't login devise for get accessToken

### ISSUE THREAD

**Issue by FordeD** [PSS-Tools-Development/pssapi.py#69]
I wanted to authorize the device via DeviceLogin15, but I get an error
`<UserLogin errorMessage="An error occurred." />`

URL Request: https://api.pixelstarships.com/UserService/DeviceLogin15
Body Request: 
```
{
  AccessToken: '00000000-0000-0000-0000-000000000000',
  AdvertisingKey: '00000000-0000-0000-0000-000000000000',
  Checksum: '4f3ec7b6658a28ba371ffd5758dac3c7',
  ClientDateTime: '2024-11-02T12:59:31', // new Date().toISOString().slice(0, -5)
  DeviceKey: 'a1cb4462-0f33-4d61-ab6c-57c78756d9e0', // random generated UUID
  DeviceType: 'DeviceTypeAndroid',
  IsJailBroken: false,
  LanguageKey: 'ru',
  RefreshToken: '',
  Signal: false,
  UserDeviceInfo: {
    ClientBuild: '',
    ClientVersion: '',
    DeviceName: 'Samsung',
    Locale: '',
    OSBuild: '',
    OsVersion: '',
  },
}
```

Where and how can I understand what checksum_key value should be used to get the checksum value?
Maybe I made a mistake somewhere with the logic?

The checksum creation logic is written in NodeJS:
```
const device_key = 'a1cb4462-0f33-4d61-ab6c-57c78756d9e0'
const timestamp = new Date().toISOString().slice(0, -5); // return '2024-11-02T12:53:24'
const checksum_key = "" // ?? where i can get this value?
const hash = crypto.createHash('md5').update(`${device_key}${timestamp}${constants.DEVICE_TYPE}${checksum_key}savysoda`);
return hash.digest('hex') // return 'a490c108d10eb1f3128bef1cf9e1a974'
```

**Comment by Zukunftsmusik** [comment]
Hey there, the `checksum_key` parameter is a "secret" that we can't share with the library at this point (we don't have the permission). However it's not that secret anymore and you can find it on github in other repos. E.g. search for **Pixel Starships DeviceLogin** ;)
